import { PolicyReport } from "./analyze";

function levelEmoji(level: "danger" | "warn" | "safe"): string {
  if (level === "danger") return "🔴";
  if (level === "warn") return "🟡";
  return "🟢";
}

function gradeText(grade: string): string {
  if (grade === "A") return "Excellent — policy follows least-privilege best practices.";
  if (grade === "B") return "Good — a few items worth reviewing.";
  if (grade === "C") return "Moderate — several risky patterns detected.";
  if (grade === "D") return "Poor — significant security concerns found.";
  return "Failing — this policy grants excessive permissions.";
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportMarkdown(report: PolicyReport, rawJson: string): void {
  const lines: string[] = [];

  lines.push("# IAM Policy Security Report");
  lines.push("");
  lines.push(`**Score:** ${report.score}/100 (Grade ${report.grade})`);
  lines.push("");
  lines.push(`> ${gradeText(report.grade)}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(
    `| Risk | Count |\n|------|-------|\n| 🔴 Critical | ${report.totalDanger} |\n| 🟡 Warning | ${report.totalWarn} |\n| 🟢 Passed | ${report.totalSafe} |`
  );
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const s of report.statements) {
    lines.push(`## Statement ${s.idx + 1}: ${s.sid}`);
    lines.push("");
    lines.push(`**Effect:** ${s.effect}`);
    lines.push(`**Risk Level:** ${levelEmoji(s.worstLevel)} ${s.worstLevel.toUpperCase()}`);
    lines.push("");
    lines.push(`**What it does:** ${s.summary}`);
    lines.push("");
    lines.push("**Actions:**");
    for (const a of s.actions) lines.push(`- \`${a}\``);
    lines.push("");
    lines.push("**Resources:**");
    for (const r of s.resources) lines.push(`- \`${r}\``);
    if (s.hasCondition) {
      lines.push("");
      lines.push("**Condition:**");
      lines.push("```json");
      lines.push(JSON.stringify(s.condition, null, 2));
      lines.push("```");
    }
    if (s.findings.length > 0) {
      lines.push("");
      lines.push("**Findings:**");
      for (const f of s.findings) lines.push(`- ${levelEmoji(f.level)} ${f.msg}`);
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("## Raw Policy");
  lines.push("");
  lines.push("```json");
  lines.push(rawJson);
  lines.push("```");
  lines.push("");
  lines.push("---");
  lines.push(`*Generated by [IAM AccessLens](https://aws-iam-accesslens.onrender.com)*`);

  downloadBlob(new Blob([lines.join("\n")], { type: "text/markdown" }), "iam-security-report.md");
}

export function exportPDF(report: PolicyReport, rawJson: string): void {
  const scoreColor = report.score >= 80 ? "#22c55e" : report.score >= 55 ? "#f59e0b" : "#ef4444";

  let statementsHtml = "";
  for (const s of report.statements) {
    const badge =
      s.worstLevel === "danger"
        ? '<span style="background:#991b1b;color:#fca5a5;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700">HIGH RISK</span>'
        : s.worstLevel === "warn"
        ? '<span style="background:#92400e;color:#fde68a;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700">REVIEW</span>'
        : '<span style="background:#166534;color:#86efac;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700">SCOPED</span>';

    const findingsList = s.findings
      .map((f) => {
        const icon = f.level === "danger" ? "⛔" : f.level === "warn" ? "⚠️" : "✅";
        return `<li style="margin-bottom:4px">${icon} ${f.msg}</li>`;
      })
      .join("");

    statementsHtml += `
      <div style="margin-bottom:24px;border:1px solid #475569;border-radius:8px;padding:16px;page-break-inside:avoid">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px">
          <strong>${s.sid}</strong>
          ${badge}
        </div>
        <p style="color:#94a3b8;margin:4px 0;font-size:13px">${s.summary}</p>
        <p style="margin:8px 0 4px;font-size:12px;color:#64748b"><b>Effect:</b> ${s.effect}</p>
        <p style="margin:4px 0;font-size:12px;color:#64748b"><b>Actions:</b> ${s.actions.join(", ")}</p>
        <p style="margin:4px 0;font-size:12px;color:#64748b"><b>Resources:</b> ${s.resources.join(", ")}</p>
        ${findingsList ? `<ul style="margin:8px 0 0;padding-left:20px;font-size:13px">${findingsList}</ul>` : ""}
      </div>`;
  }

  const html = `<!DOCTYPE html>
<html>
<head>
  <style>
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
  </style>
</head>
<body style="font-family:-apple-system,'Segoe UI',sans-serif;background:#0f172a;color:#f1f5f9;padding:32px;max-width:800px;margin:0 auto">
  <h1 style="font-size:22px;margin:0 0 4px">IAM Policy Security Report</h1>
  <p style="color:#94a3b8;font-size:13px;margin:0 0 16px">Generated by IAM AccessLens</p>

  <div style="display:flex;gap:24px;align-items:center;margin-bottom:24px;padding:16px;background:#1e293b;border:1px solid #475569;border-radius:8px">
    <div style="text-align:center;min-width:80px">
      <div style="font-size:36px;font-weight:800;color:${scoreColor}">${report.score}</div>
      <div style="font-size:12px;color:#64748b">Grade ${report.grade}</div>
    </div>
    <div style="border-left:1px solid #475569;padding-left:24px">
      <p style="margin:0 0 4px;font-size:14px">${gradeText(report.grade)}</p>
      <p style="margin:0;font-size:13px;color:#94a3b8">
        <span style="color:#ef4444">${report.totalDanger} critical</span> ·
        <span style="color:#f59e0b">${report.totalWarn} warning</span> ·
        <span style="color:#22c55e">${report.totalSafe} passed</span>
      </p>
    </div>
  </div>

  <h2 style="font-size:16px;margin:24px 0 12px">Statement Analysis</h2>
  ${statementsHtml}

  <h2 style="font-size:16px;margin:24px 0 12px">Raw Policy</h2>
  <pre style="background:#1e293b;border:1px solid #475569;border-radius:8px;padding:12px;font-size:11px;overflow-x:auto;white-space:pre-wrap">${rawJson}</pre>

  <p style="margin-top:24px;font-size:11px;color:#64748b;text-align:center">
    Generated by <a href="https://aws-iam-accesslens.onrender.com" style="color:#6366f1">IAM AccessLens</a>
  </p>
</body>
</html>`;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 300);
  }
}
