import { PolicyReport } from "./analyze";

function levelEmoji(level: "danger" | "warn" | "safe"): string {
  if (level === "danger") return "🔴";
  if (level === "warn") return "🟡";
  return "🟢";
}

export function exportReport(report: PolicyReport, rawJson: string): void {
  const lines: string[] = [];

  lines.push("# IAM Policy Security Report");
  lines.push("");
  lines.push(`**Score:** ${report.score}/100 (Grade ${report.grade})`);
  lines.push("");
  lines.push(
    `> ${
      report.grade === "A"
        ? "Excellent — policy follows least-privilege best practices."
        : report.grade === "B"
        ? "Good — a few items worth reviewing."
        : report.grade === "C"
        ? "Moderate — several risky patterns detected."
        : report.grade === "D"
        ? "Poor — significant security concerns found."
        : "Failing — this policy grants excessive permissions."
    }`
  );
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(
    `| Risk | Count |\n|------|-------|\n| 🔴 Critical | ${report.totalDanger} |\n| 🟡 Warning | ${report.totalWarn} |\n| 🟢 Passed | ${report.totalSafe} |`
  );
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const s of report.statements) {
    lines.push(`## Statement ${s.idx + 1}: ${s.sid}`);
    lines.push("");
    lines.push(`**Effect:** ${s.effect}`);
    lines.push(`**Risk Level:** ${levelEmoji(s.worstLevel)} ${s.worstLevel.toUpperCase()}`);
    lines.push("");
    lines.push(`**What it does:** ${s.summary}`);
    lines.push("");
    lines.push("**Actions:**");
    for (const a of s.actions) {
      lines.push(`- \`${a}\``);
    }
    lines.push("");
    lines.push("**Resources:**");
    for (const r of s.resources) {
      lines.push(`- \`${r}\``);
    }
    if (s.hasCondition) {
      lines.push("");
      lines.push("**Condition:**");
      lines.push("```json");
      lines.push(JSON.stringify(s.condition, null, 2));
      lines.push("```");
    }
    if (s.findings.length > 0) {
      lines.push("");
      lines.push("**Findings:**");
      for (const f of s.findings) {
        lines.push(`- ${levelEmoji(f.level)} ${f.msg}`);
      }
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("## Raw Policy");
  lines.push("");
  lines.push("```json");
  lines.push(rawJson);
  lines.push("```");
  lines.push("");
  lines.push("---");
  lines.push(
    `*Generated by [IAM Visualizer](https://github.com/Enelination/aws-iam-accesslens)*`
  );

  const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "iam-security-report.md";
  a.click();
  URL.revokeObjectURL(url);
}
